### PR TITLE
issue #19

### PR DESCRIPTION
**Pull request by tmjee**
Fix issue #19

### CODE REVIEW

**Comment by dmarkov** [comment]
@tmjee I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by dmarkov** [comment]
@yegor256 pull request is rather short, review it please

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by dmarkov** [comment]
@yegor256 Thanks so much! Your account was topped up for **16 mins** (transaction ID is `000-66a053ed`, the task took 23 hours and 5 mins)... you're getting extra minutes here (c=1)... +16 to your rating, your total score is [+13633](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
