### PR TITLE
Add automatic version detection to Javadoc badge

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by dmarkov** [comment]
@valery1707 Thanks, someone will review your pull request soon

**Comment by dmarkov** [comment]
@yegor256 pull request is rather short, review it please

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 I just added **16 mins** to your account, many thanks for your contribution (000-9ab2ed52).. 98 hours and 13 mins spent here... you're getting extra minutes here (c=1)... +16 added to your rating, current score is: [+4416](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
