### PR TITLE
Skeleton of JSON and YAML validation.

### PR DESCRIPTION
**Pull request by dpisarenko**
Issue https://github.com/jcabi/jcabi-beanstalk-maven-plugin/issues/2

### CODE REVIEW

**Comment by dpisarenko** [comment]
@dmarkov Please find someone to review this pull request.

**Comment by dmarkov** [comment]
I'll find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by dmarkov** [comment]
@carlosmiranda it's yours, please review

**Comment by carlosmiranda** [comment]
@dpisarenko I don't like the design. It appears that `protected` methods `createZipFile`, `readFile`, and `createServerCredentials` are added in `AbstractBeanstalkMojo` for the sake of unit test mocking. In other instances, it makes the class unnecessarily complex.

Perhaps it's better if we create a separate fake object class that extends `AbstractBeanstalkMojo`. See http://www.yegor256.com/2014/09/23/built-in-fake-objects.html. That will also simplify our unit test class.

**Comment by dpisarenko** [comment]
@carlosmiranda How can I mock, for examle `final ZipFile warfile = new ZipFile(this.war);` using a fake class subclass of `AbstractBeanstalkMojo`?

**Comment by carlosmiranda** [comment]
@dpisarenko In that case, you are using the directory given by the field `war`, and you have access to that field. Why not use it in that manner, considering that it's the class' intended usage?

We should not couple the class too tightly with the unit tests. Otherwise, changing one will risk breaking the other, without any benefits to us with respect to functionality.

**Comment by dpisarenko** [comment]
@carlosmiranda Do you mean the following:

I create a class `WarFile` in which the actual validation happens.

public class WarFile {
	private final File war;

	public WarFile(final File file) {
		this.war = file;
	}

	public boolean ebextensionsValid() {
		// Check the validity of ebextensions here
	}
}

Then, in `com.jcabi.beanstalk.maven.plugin.AbstractBeanstalkMojo#execute` I'd put this:

```
if (!new WarFile(this.war).ebextensionsValid()) {
    throw new MojoFailureException(
        String.format(".ebextensions invalid")
    );
}
```

Would such design be better?

**Comment by carlosmiranda** [comment]
@dpisarenko Yes, that makes sense to me. That way we're going to have two smaller, better defined classes instead of one big class that tries to do everything.

**Comment by dpisarenko** [comment]
@carlosmiranda I modified the code as discussed, but now I'm getting `DesignForExtensionCheck` errors because the class and the methods are non-final in order to test them with Mockito. What can I do in order for my code to pass Checkstyle checks and be tested?

**Comment by carlosmiranda** [comment]
@dpisarenko Declare `WarFile` to be a `final class`. :)

**Comment by dpisarenko** [comment]
@carlosmiranda Let's say we do this. If I have a final `ValidatingWarFile`, I cannot test its internals in a unit test.

Then there are several choices:

  1. Create interfaces for JSON and YAML validators, inject them via constructor and then check that they are called. Drawback: Additional interfaces/classes.
  1. Forget about the tests, which test the internals altogether. Drawback: Lowers the quality.
  1. Create WAR files (one correct, one with invalid YAML, one with invalid JSON) on disk and run the `ValidatingWarFile` over them.

**Comment by dpisarenko** [comment]
@carlosmiranda Another possibly useful option is to change constructor from `WarFile(final File file)` to `WarFile(final ZipFile zipFile)` and call it like this: `new WarFile(new ZipFile(this.war))...`.

**Comment by carlosmiranda** [comment]
@dpisarenko Yes, I agree with changing the constructor. If there's a complex object whose interaction we need to test, better to supply it from outside for design cohesion.

**Comment by dpisarenko** [comment]
@carlosmiranda Please look at the modified code.

**Comment by carlosmiranda** [comment]
@rultor Can we merge?

**Comment by dmarkov** [comment]
@carlosmiranda I added **20 mins** to your account, many thanks for working with the project!... +20 added to your rating, at the moment it is: [+2219](http://www.netbout.com/b/35023?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
