### PR TITLE
Added @Cacheable annotation with test

### PR DESCRIPTION
**Pull request by cyberone**

### CODE REVIEW

**Comment by dmarkov** [comment]
Many thanks for the PR, let me find a reviewer for it

**Comment by dmarkov** [comment]
@yegor256 please review this PR

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by dmarkov** [comment]
@yegor256 thanks, paid, **16 mins** to your account, payment ID is `000-c850954a`... +16 added to your rating, current score is: [+4476](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
